sign_up:
  path: /signUp
  controller: App\Controller\UserController::register

login_page:
  methods: GET
  path: /login
  controller: App\Controller\SecurityController::loginPage

login_check:
  methods: POST
  path: /signIn
  controller: App\Controller\SecurityController::authLogin

logout:
  path: /logout
  controller: App\Controller\SecurityController::logout