create_post_page:
  path: /{linkName}/add-post
  methods: GET
  controller: App\Controller\PostController::createPostPage

create_post:
  path: /create-post
  methods: POST
  controller: App\Controller\PostController::createPost

delete_post:
  path: /{postId}/delete-post
  methods: POST
  controller: App\Controller\PostController::deletePost